name = "maz-qzz-io"
compatibility_date = "2024-01-01"

[build]
command = "npm run build"

[build.upload]
format = "modules"
dir = ".vercel/output"

[[redirects]]
from = "/*"
to = "/index.html"
status = 200